name: my-first-workflow

on: push

jobs: 
    first_job:
        runs-on: ubuntu-22.04

        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: List and read file
              run: |
                echo "This is my first workflow"
                ls -lrta
                cat README.md
