name: Generate Ascii Artwork 

on: push

jobs: 
    ascii_job:
     runs-on: ubuntu-22.04

     steps:
        - name: checkout Repo
          uses: actions/checkout@v4

        - name: Checkout Repo files
          run: ls

        - name: execute scripts
          run: |
            chmod +x ascii-script.sh
            ./ascii-script.sh
        
       


