name: sequence

on: push

jobs: 
    build_job_1:
        runs-on: ubuntu-22.04
        steps:
        - name: Install Cowsay Program
          run: sudo apt-get install cowsay -y

        - name: Execute Cowsay CMD
          run: cowsay -f dragon "Run for Cover, I am a dragon ...RAWRRR" >> dragon.txt

        
        
        - name: Uploading dragon.txt
          uses: actions/upload-artifact@v4
          with:
            name: dragon-text-file
            path: dragon.txt
          

    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-22.04
        steps:

        - uses: actions/download-artifact@v4
          with:
            name: dragon-text-file

       
        - name: Test File Exists
          run: grep -i "dragon" dragon.txt

          

    deploy_job_3:
        needs: test_job_2
        runs-on: ubuntu-22.04
        steps:  
        - uses: actions/download-artifact@v4
          with:
             name: dragon-text-file
     

        - name: Read File
          run: cat dragon.txt

        - name: Deploy
          run: echo Deploying...