name: sequence

on: push

jobs: 
    buikd_job_1:
        runs-on: ubuntu-22.04
        steps:
        - name: Install Cowsay Program
          run: sudo apt-get install cowsay -y

        - name: Execute Cowsay CMD
          run: cowsay -f dragon "Run for Cover, I am a dragon ...RAWRRR >> dragon.txt"

        
        - name: Sleep for 30 seconds
          run: sleep 30
          

    test_job_2:
        runs-on: ubuntu-22.04
        steps:
        - name: Sleep for 10 seconds
          run: sleep 10

        - name: Test File Exists
          run: grep -i "dragon" dragon.txt

          
          
    deploy_job_3:
        runs-on: ubuntu-22.04
        steps:
        - name: Read File
          run: cat dragon.txt

        - name: Deploy
          run: echo Deploying..